// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCreO2NLz2LL7crk3Wg4MpuuEeSAcFsBEg',
    appId: '1:26873241219:web:d92104e7b34bfd01e905b6',
    messagingSenderId: '26873241219',
    projectId: 'ogame-vault',
    authDomain: 'ogame-vault.firebaseapp.com',
    storageBucket: 'ogame-vault.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6EOe7RjfKmXwySIHJxjB7zQcWKitZinU',
    appId: '1:26873241219:android:511533b1de390927e905b6',
    messagingSenderId: '26873241219',
    projectId: 'ogame-vault',
    storageBucket: 'ogame-vault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY5pyjaYLTKxo3HtyjpJuEESsJtRS8IV8',
    appId: '1:26873241219:ios:a269e5cdd68bb0f0e905b6',
    messagingSenderId: '26873241219',
    projectId: 'ogame-vault',
    storageBucket: 'ogame-vault.firebasestorage.app',
    iosClientId: '26873241219-cvb5t8nei3qe63js4og5foeh94asbbk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY5pyjaYLTKxo3HtyjpJuEESsJtRS8IV8',
    appId: '1:26873241219:ios:a269e5cdd68bb0f0e905b6',
    messagingSenderId: '26873241219',
    projectId: 'ogame-vault',
    storageBucket: 'ogame-vault.firebasestorage.app',
    iosClientId: '26873241219-cvb5t8nei3qe63js4og5foeh94asbbk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCreO2NLz2LL7crk3Wg4MpuuEeSAcFsBEg',
    appId: '1:26873241219:web:ea97350436b6edc3e905b6',
    messagingSenderId: '26873241219',
    projectId: 'ogame-vault',
    authDomain: 'ogame-vault.firebaseapp.com',
    storageBucket: 'ogame-vault.firebasestorage.app',
  );
}
